### PR TITLE
Add support for downloading PDFs...

### PR DESCRIPTION
**Pull request by porn**
for:
- invoices
- estimates
- sales receipts

Resolves: https://github.com/sidecars/python-quickbooks/issues/14

### CODE REVIEW

**Comment by ej2** [comment]
Looks good. If you will write tests to cover the new code I will merge it in. Thanks!

**Comment by porn** [comment]
Do you think it'd be sufficient to download PDF in the `tests/integration/test_invoice.py`? In order to get the pdf the invoice/sales receipt needs to be stored in the quickbooks.

**Comment by porn** [comment]
Hi again!

I tried my best to cover as much as possible, but I don't know how to hit the remaining line. Also he situation in `download_pdf()` method of the `client.py` file is very similar to the `make_request()` where the line isn't covered neither.

Can you please check and merge or help me with the tests coverage?

**Comment by porn** [comment]
Cool, I managed to cover the remaining line with a help of my colleague.

And what more! I also increased the coverage of `make_request` method :wink:.

Can you now please merge my changes in and create a new release so we can use it right away?

**Comment by ej2** [comment]
Excellent work. I will merge it in.

**Pull request merged**
